name: Frontend

on:
  push:
    branches: [master]
    paths:
      - "frontend/**"
      - "package.json"
      - "yarn.lock"
      - ".github/actions/setup/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [master]
    paths:
      - "frontend/**"
      - "package.json"
      - "yarn.lock"
      - ".github/actions/setup/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          uv-sync: "false"
      - run: yarn format:frontend:check
      - run: yarn lint:frontend
      - run: yarn typecheck
      - run: yarn test:frontend
      - run: yarn build:frontend
